FROM fedora:latest

RUN dnf update -y && \
    dnf install -y ansible

RUN dnf install -y passwd \
    && useradd -m -s /bin/bash admin \
    && echo "admin ALL=(ALL) ALL" >> /etc/sudoers \
    && passwd -d root

RUN echo 'admin:admin' | chpasswd

USER admin
WORKDIR /home/admin

COPY --chown=admin . init
WORKDIR init

CMD ["/bin/bash"]
