- hosts: localhost
  tasks:
    - include: tasks/dependencies.yml
    - include: tasks/zsh.yml
    - include: tasks/ssh.yml
    - include: tasks/node.yml
    - include: tasks/sdkman.yml
    - include: tasks/dotfiles.yml
