- name: Fetch nvm installation script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh
    dest: /tmp/nvm_install.sh
    mode: '0755'
  tags:
    - node

- name: Run nvm installation script
  ansible.builtin.command: /tmp/nvm_install.sh
  changed_when: true
  tags:
    - node
