- name: Fetch sdkman installation script
  ansible.builtin.get_url:
    url: https://get.sdkman.io
    dest: /tmp/sdkman_install.sh
    mode: '0755'
  tags:
    - sdkman

- name: Run sdkman installation script
  ansible.builtin.command: /tmp/sdkman_install.sh
  changed_when: true
  tags:
    - sdkman
